[package]
name = "osufuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osu-beatmap-parser = { git = "https://github.com/SailorSnoW/osu-beatmap-parser/", version = "0.14.0" }
brainfuck = "0.2.1"
